name: Main Tests

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.2.0

    - name: Set up julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.11.1

    - name: Install package
      run: |
        julia --project=@. -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

    - name: Run Unit Tests
      run: |
        julia --project=@. -e 'using Pkg; Pkg.test()'
      
